qso/urls.py
from django.conf.urls.defaults import patterns, include, url

from qso.views import HomeView,ContactLogView

urlpatterns = patterns('',
    # Examples:
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^log/(?P<pk>\d+)/$', ContactLogView.as_view(), name='contact_log'),

)

urls.py
from django.conf.urls.defaults import patterns, include, url

from django.views.generic.simple import redirect_to
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', redirect_to, {'url': '/mooselogger/'}),
    url(r'^mooselogger/', include('mooselogger.qso.urls')),
    url(r'^callsign/', include('mooselogger.qrz.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

qso/models.py
from django.db import models
from django.core.exceptions import ValidationError

class BandManager(models.Manager):
    def get_band_for_frequency(self, freq):
        try:
           band = Band.objects.filter(band_bottom__lte=freq, band_top__gte=freq)[0]
        except IndexError:
           band = None

        return band

class Band(models.Model):
    objects = BandManager()

    name = models.CharField(max_length=30,unique=True)
    band_bottom = models.DecimalField(max_digits = 8, decimal_places=3)
    band_top = models.DecimalField(max_digits = 8, decimal_places=3)

    def clean(self):
        if self.band_bottom > self.band_top:
            raise ValidationError('Band bottom must be lower than band top.')

    def save(self, *args, **kwargs):
        self.full_clean()
        
        super(Band,self).save(*args,**kwargs)

    def __unicode__(self):
        return self.name

class Mode(models.Model):
    name = models.CharField(max_length=30,unique=True)

    def __unicode__(self):
        return self.name

class Operator(models.Model):
    callsign = models.CharField(max_length=10)

    def __unicode__(self):
        return self.callsign

class QRZCredentials(models.Model):
    operator = models.ForeignKey(Operator)
    username = models.CharField(max_length=40)
    password = models.CharField(max_length=40,help_text='NOTE: stored in plaintext!')

    def __unicode__(self):
	return self.username


class Ruleset(models.Model):
    name = models.CharField(unique=True, max_length=255)
    created_on = models.DateTimeField(auto_now_add=True)

    is_contest = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

class ContactLog(models.Model):
    name = models.CharField(max_length=255)
    ruleset = models.ForeignKey(Ruleset)
    owner = models.ForeignKey(Operator)
    created_on = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

class Contact(models.Model):
    contact_log = models.ForeignKey(ContactLog)
    operator = models.ForeignKey(Operator)

    when = models.DateTimeField()
    callsign = models.CharField(max_length=10)
    frequency = models.DecimalField(max_digits = 9, decimal_places=4,null=True,blank=True)
    mode = models.ForeignKey(Mode)
    band = models.ForeignKey(Band)
    rst_sent = models.CharField(max_length=3,null=True,blank=True)
    rst_received = models.CharField(max_length=3,null=True,blank=True)
    contest_exchange_sent = models.CharField(max_length=100, null=True,blank=True)
    contest_exchange_received = models.CharField(max_length=100, null=True,blank=True)

    def __unicode__(self):
        return u'%s, %s' % (self.when, self.callsign)

    

qso/forms.py
import datetime

from django import forms

from qso.models import Contact,Mode,Band,QRZCredentials

VALID_RST_RE = '^[1-5][1-9N][1-9N]?$'

class ContactForm(forms.Form):
    when = forms.DateTimeField(required=False)
    callsign = forms.CharField(max_length=10,
                               widget=forms.TextInput(attrs={'size':'10'}),
                               error_messages={'required': 'Please provide the contact\'s callsign.'})
    frequency = forms.CharField(required=False,
                               widget=forms.TextInput(attrs={'size':'10'}))
    mode = forms.ModelChoiceField(queryset=Mode.objects.all(),
                                  error_messages={'required': 'Please select a mode.'})
    band = forms.ModelChoiceField(queryset=Band.objects.all(),required=False)
    rst_sent = forms.RegexField(required=False,
                                regex=VALID_RST_RE,
                                widget=forms.TextInput(attrs={'size':'3'}),
                                error_messages={'invalid': 'RST Sent should be in the format 59 or 599.'})
    rst_received = forms.RegexField(required=False,
                                regex=VALID_RST_RE,
                                widget=forms.TextInput(attrs={'size':'3'}),
                                error_messages={'invalid': 'RST Received should be in the format 59 or 599.'})

    def get_fieldless_errors(self):
        return self.errors.get('__all__')

    def clean_frequency(self):
        freq = self.cleaned_data.get('frequency')

        if freq:
            try:
                if float(freq) < 0:
                    raise forms.ValidationError('Frequency must be positive.')
            except ValueError:
                raise forms.ValidationError('Please enter frequency in the format 7.123')

        return freq

    def clean_when(self):
        when = self.cleaned_data.get('when')

        if not when:
            when = datetime.datetime.utcnow()

        return when

    def clean(self):
        if not self.cleaned_data.get('band'):
          freq = self.cleaned_data.get('frequency')

          if not freq:
            band = None
          else:
            band = Band.objects.get_band_for_frequency(freq)
            
          if not band:
            raise forms.ValidationError('Please select a band or enter a frequency.')
          else:
            self.cleaned_data['band'] = band

        return self.cleaned_data

    def save(self, contact_log, operator):

        contact = Contact(contact_log=contact_log,
                                         operator=operator,
                                         callsign=self.cleaned_data['callsign'],
                                         band=self.cleaned_data['band'],
                                         mode=self.cleaned_data['mode'],
                                         when=self.cleaned_data['when'],
                                         rst_sent=self.cleaned_data['rst_sent'],
                                         rst_received=self.cleaned_data.get('rst_received'),
                                         contest_exchange_sent=self.cleaned_data.get('contest_exchange_sent'),
                                         contest_exchange_received=self.cleaned_data.get('contest_exchange_received'))

        if self.cleaned_data.get('frequency'):
            contact.frequency = self.cleaned_data.get('frequency')

        contact.save()

        return contact    

class ContestForm(ContactForm):
    contest_exchange_sent = forms.CharField(required=False,
                                widget=forms.TextInput(attrs={'size':'10'}))
    contest_exchange_received = forms.CharField(required=False,
                                widget=forms.TextInput(attrs={'size':'10'}))


class QRZCredentialsAdminForm(forms.ModelForm):
	password = forms.CharField( widget=forms.PasswordInput )

	class Meta:
		model = QRZCredentials

qso/views.py
from django.shortcuts import render_to_response
from django.views.generic import ListView, DetailView, View
from django.shortcuts import get_object_or_404
from django.template import RequestContext

from qso.models import Ruleset, ContactLog, Operator, Contact,QRZCredentials

from qso.forms import ContactForm,ContestForm

class HomeView(ListView):
    context_object_name = "logs"
    template_name = "home.html"

    def get_queryset(self):
        return ContactLog.objects.all().order_by('name')

class ContactLogView(View):
    template_name = "contact_log.html"
    context_object_name = "contact_log"
    form_class = ContactForm

    queryset = ContactLog.objects.all()
    
    def get_operator(self):
        return Operator.objects.get(callsign='KC2ZUF')  
   
    def get_qrz_info(self):
	try:
	    info = QRZCredentials.objects.filter(operator=self.get_operator)[0]
	    return (info.username, info.password)
	except IndexError:
	    pass
  
        return None

    def get_context_data(self, **kwargs):
        context = {}

        cl = get_object_or_404(ContactLog, pk=kwargs['pk'])
        context['contact_log'] = cl
        context['contacts'] = Contact.objects.filter(contact_log=cl).order_by('-when')

        return context 

    def dispatch(self, request, *args, **kwargs):
        ctx = self.get_context_data(**kwargs)
        form = None
        form_cls = ContactForm
        if ctx['contact_log'].ruleset.is_contest:
	     form_cls = ContestForm

	if not request.session.get('qrz_info'):
	    request.session['qrz_info'] = self.get_qrz_info()

        if request.POST:
            form = form_cls(data=request.POST)

            if form.is_valid():
                form.save(contact_log=ctx['contact_log'],
                          operator=self.get_operator())
        else:
            form = form_cls()

        ctx['form'] = form

        return render_to_response('contact_log.html', 
                                 ctx,
                                 RequestContext(request))
       

qso/templates/base.html
<html>
<head>
<title>MooseLogger: {% block page_title %}{% endblock %}</title>
<script type="text/javascript" src="/static/jquery-1.6.2.min.js"></script>
{% block head_extra %}{% endblock %}
<body>
<h1>{% block section_title %}{% endblock %}</h1>
{% block page_content %}{% endblock %}
</body>
</html>

qso/templates/contact_log.html
{% extends "base.html" %}

{% block page_title %}{{ contact_log.name }}{% endblock %}

{% block section_title %}{{ contact_log.name }}{% endblock %}

{% block head_extra %}
<script language="JavaScript">
$(document).ready(function() {
    $('#id_callsign').change(function() {
        callsign =  $('#id_callsign').val();
        if (callsign && callsign.length > 2) {
            $('#qrz_area').load('/callsign/lookup/' + document.forms.contact_form.callsign.value + '/');
        }
    });
});
</script>
<style type="text/css">
table.contact_table {
    border-left: 1px solid;
    border-top: 1px solid;
}

th.contact_table  {
    border-bottom: 1px solid;
    border-right: 1px solid;
    padding: 5px;
}

td.contact_table  {
    border-bottom: 1px solid;
    border-right: 1px solid;
    padding: 5px;
    vertical-align: top;
}

tr.odd {
    background: #CCCCCC;
}

ul.errorlist {
    list-style-type: none;
    padding-left: 0px;
    font-size: 0.75em;
}
</style>

{% endblock %}

{% block page_content %}

<form action="." method="POST" name="contact_form">
{% csrf_token %}

<table class="contact_table" cellspacing="0" cellpadding="0" width="100%">
 <tr>
  <th class="contact_table">Date</th>
  <th class="contact_table">Time</th>
  <th class="contact_table">Callsign</th>
  <th class="contact_table">Mode</th>
  <th class="contact_table">Frequency</th>
  <th class="contact_table">Band</th>
  <th class="contact_table">RST Sent</th>
  <th class="contact_table">RST Recv</th>
{% if contact_log.ruleset.is_contest %}<th class="contact_table">Contest Sent</th>
  <th class="contact_table">Contest Recv</th>{% endif %}
  <th class="contact_table"></th>
 </tr>
{% if not contacts %}<tr><td colspan="10">You have not logged any entries yet.</td></tr>{% endif %}
<tr class="{% cycle 'odd' 'even' %}">
  <td class="contact_table" colspan="2">{{ form.when }}{% if form.errors %}<br/> {{ form.errors.when }} {{ form.get_fieldless_errors }}{% endif %}</td>
  <td class="contact_table">{{ form.callsign }}{% if form.errors %}<br/> {{ form.errors.callsign }} {% endif %}
<br/>
<div id="qrz_area"></div>
</td>
  <td class="contact_table">{{ form.mode }}{% if form.errors %}<br/> {{ form.errors.mode }} {% endif %}</td>
  <td class="contact_table">{{ form.frequency }} MHz{% if form.errors %}<br/> {{ form.errors.frequency }} {% endif %}</td>
  <td class="contact_table">{{ form.band }}{% if form.errors %}<br/> {{ form.errors.band }} {% endif %}</td>
  <td class="contact_table">{{ form.rst_sent }}{% if form.errors %}<br/> {{ form.errors.rst_sent }} {% endif %}</td>
  <td class="contact_table">{{ form.rst_received }}{% if form.errors %}<br/> {{ form.errors.rst_received }} {% endif %}</td>
{% if contact_log.ruleset.is_contest %}<td class="contact_table">{{ form.contest_exchange_sent }}{% if form.errors %}<br/> {{ form.errors.contest_exchange_sent }} {% endif %}</td>
  <td class="contact_table">{{ form.contest_exchange_received }}{% if form.errors %}<br/> {{ form.errors.contest_exchange_received }} {% endif %}</td>{% endif %}
  <td class="contact_table"><input type="submit" value="Add"/></td>
 </tr>
{% for contact in contacts %}
 <tr class="{% cycle 'odd' 'even' %}">
  <td class="contact_table">{{ contact.when|date:"m/d/Y" }}</td>
  <td class="contact_table">{{ contact.when|time:"H:i" }}Z</td>
  <td class="contact_table">{{ contact.callsign|upper }}</td>
  <td class="contact_table">{{ contact.mode }}</td>
  <td class="contact_table">{{ contact.frequency }} MHz</td>
  <td class="contact_table">{{ contact.band }}</td>
  <td class="contact_table">{{ contact.rst_sent }}</td>
  <td class="contact_table">{{ contact.rst_received }}</td>
{% if contact_log.ruleset.is_contest %}  <td class="contact_table">{{ contact.contest_exchange_sent }}</td>
  <td class="contact_table">{{ contact.contest_exchange_received }}</td>{% endif %}
  <td class="contact_table"></td>
 </tr>
{% endfor %}
</table>

</form>
{% endblock %}

qso/templates/home.html
{% extends "base.html" %}

{% block page_title %}Home{% endblock %}

{% block section_title %}Home{% endblock %}

{% block page_content %}
{% if not logs %}<p>You have not set up any contact logs.</p>{% else %}
<ul>
{% for l in logs %}
<li><a href="{% url contact_log l.id %}">{{ l.name }}</a></li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}